# Generated by Django 4.1.7 on 2023-02-24 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "source",
                    models.CharField(
                        max_length=256, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("template", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("form_data", models.TextField()),
                (
                    "form_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="source_template.formtemplate",
                    ),
                ),
            ],
        ),
    ]
